WebApplication/Controllers/PitangueiraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using WebApplication.DTO;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class PitangueiraController : Controller
    {
        private readonly PitangueiraContext _context;

        public PitangueiraController(PitangueiraContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer" , accessToken);
            string jsonRes = await httpClient.GetStringAsync("https://localhost:44391/api/Employee/Task");

            if (jsonRes == null)
            {
                return View();
            }

            var res = JsonConvert.DeserializeObject<Employee>(jsonRes);
            return View(res);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonRes = await httpClient.GetStringAsync("https://localhost:44391/api/Employee/Types");
            var res = JsonConvert.DeserializeObject<List<AttenType>>(jsonRes);
            ViewData["TypeName"] = new SelectList(res, "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Clients,Comments, Type")] AttendanceCreate Attendance)
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");

            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            StringContent content = new StringContent(JsonConvert.SerializeObject(Attendance), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44391/api/Employee/CreateTask/", content);
            var status = response.IsSuccessStatusCode;
            if (status)
                return Redirect("/Pitangueira/Index/");
            return View();
        }

        public async Task<IActionResult> Types()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonRes = await httpClient.GetStringAsync("https://localhost:44391/api/Employee/TypesManagement");


            var res = JsonConvert.DeserializeObject<EmployeewTypes>(jsonRes);
            return View(res);
        }

        public IActionResult CreateType()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTypeAsync([Bind("Name")] AttenType attendanceType)
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");

            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            StringContent content = new StringContent(JsonConvert.SerializeObject(attendanceType), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44391/api/Employee/CreateType/", content);
            var status = response.IsSuccessStatusCode;
            if (status)
                return Redirect("/Pitangueira/Types/");

            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");

            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            StringContent content = new StringContent(JsonConvert.SerializeObject(id), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44391/api/Employee/DeleteTask/", content);
            return Redirect("/Pitangueira/Index/");
        }

        public async Task<IActionResult> DeleteType(int id)
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");

            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            StringContent content = new StringContent(JsonConvert.SerializeObject(id), Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync("https://localhost:44391/api/Employee/DeleteType/", content);
            return Redirect("/Pitangueira/Types/");
        }

        public async Task<IActionResult> Relatory()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            if (accessToken == null || String.Empty == accessToken)
                return Redirect("/Pitangueira/Logout/");
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonRes = await httpClient.GetStringAsync("https://localhost:44391/api/Employee/AllTasks");


            var res = JsonConvert.DeserializeObject<EmployeeRelatory>(jsonRes);

            return View(res);
        }

        public IActionResult LogOut() 
        {
            HttpContext.Session.Clear();
            return Redirect("/Home/Index/");
        }

    }
}

WebApplication/Views/Pitangueira/Create.cshtml
@model WebApplication.DTO.AttendanceCreate

@{
    ViewData["Title"] = "Create";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pitangueira" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1>Register</h1>

        <h4>Attendance</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Clients" class="control-label"></label>
                        <input asp-for="Clients" class="form-control" />
                        <span asp-validation-for="Clients" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comments" class="control-label"></label>
                        <input asp-for="Comments" class="form-control" />
                        <span asp-validation-for="Comments" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Type" class="control-label">Type</label>
                        <select asp-for="Type" class="form-control" asp-items="ViewBag.TypeName"></select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

WebApplication/Views/Pitangueira/CreateType.cshtml
@model WebApplication.Models.AttenType

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pitangueira" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1>Register</h1>

        <h4>Type</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="CreateType">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="CreateType" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Types">Back to List</a>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

WebApplication/Views/Pitangueira/Index.cshtml
@model WebApplication.Models.Employee
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pitangueira" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <p class="nav-link text-dark">Welcome , @Model.UserName</p>
                        </li>
                        @{
                            if (Model.Role.Name == "Manager")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Types">Types</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Relatory">Relatory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <p>
                <a asp-controller="Pitangueira" asp-action="Create">Add Task</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <p>Id</p>
                        </th>
                        <th>
                            <p>Name</p>
                        </th>
                        <th>
                            <p>Comments</p>
                        </th>
                        <th>
                            <p>Client</p>
                        </th>
                        <th>
                            <p>Date</p>
                        </th>
                        <th>
                            <p>Type</p>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{ if (Model.Attendances != null)
                        {
                            foreach (var item in Model.Attendances)
                            {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Id)
                                            </td>
                                            <td>
                                                <p>@Model.UserName</p>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Comments)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Client)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ExecutionDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Type.Name)
                                            </td>
                                            <td>
                                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                            </td>
                                        </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

WebApplication/Views/Pitangueira/Relatory.cshtml
@model WebApplication.DTO.EmployeeRelatory
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <style>
        .invisible{
            display:none;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pitangueira" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <p class="nav-link text-dark">Welcome , @Model.Name</p>
                        </li>
                        @{
                            if (Model.Role == "Manager")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Types">Types</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Relatory">Relatory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="input-group">
                <div class="form-outline">
                    <label class="form-label" for="form1">Search</label>
                    <input type="search" id="filterTb" class="form-control" />
                    <label>Filter by:</label>
                    <select class="form-control" id="select">
                        <option value="Employee" selected> Employee</option>
                        <option value="Client"> Client</option>
                        <option value="Type"> Type</option>
                    </select>
                </div>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <p>Id</p>
                        </th>
                        <th>
                            <p>Name</p>
                        </th>
                        <th>
                            <p>Comments</p>
                        </th>
                        <th>
                            <p>Client</p>
                        </th>
                        <th>
                            <p>Date</p>
                        </th>
                        <th>
                            <p>Type</p>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{ if (Model.Attendances != null)
                        {
                            foreach (var item in Model.Attendances)
                            {
                                <tr class="Task">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td class="tecName" >
                                        @Html.DisplayFor(modelItem => item.Employee.UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Comments)
                                    </td>
                                    <td class="Client">
                                        @Html.DisplayFor(modelItem => item.Client)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ExecutionDate)
                                    </td>
                                    <td class="type">
                                        @Html.DisplayFor(modelItem => item.Type.Name)
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        var campoFiltro = document.querySelector("#filterTb");

        campoFiltro.addEventListener("input", function () {
            var Nodes = document.querySelectorAll(".Task");

            var select = document.getElementById('select');
            var value = select.options[select.selectedIndex].value;

            if (this.value.length > 0) { // se eu digitar

                for (var i = 0; i < Nodes.length; i++) {

                    var actual = Nodes[i];
                    var queryValue = ".tecName"
                    switch (value) {
                        case 'Employee':
                            queryValue = ".tecName";
                            break;
                        case 'Client':
                            queryValue = ".Client";
                            break;
                        case 'Type':
                            queryValue = ".type";
                            break;
                    }
                    var tdN = actual.querySelector(queryValue);
                    var n = tdN.textContent;
                    var express = new RegExp(this.value, "i");

                    if (!express.test(n)) {
                        actual.classList.add("invisible");
                    } else {
                        actual.classList.remove("invisible");
                    }
                }
            } else {
                for (var i = 0; i < Nodes.length; i++) {
                    var actual = Nodes[i];
                    actual.classList.remove("invisible");
                }
            }
        });
    </script>
</body>
</html>

WebApplication/Views/Pitangueira/Types.cshtml
@model WebApplication.DTO.EmployeewTypes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pitangueira" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <p class="nav-link text-dark">Welcome , @Model.UserName</p>
                        </li>
                        @{
                            if (Model.Role.Name == "Manager")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="CreateType">Types</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Relatory">Relatory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pitangueira" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <p>
                <a asp-controller="Pitangueira" asp-action="CreateType">Add Type</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <p>Id</p>
                        </th>
                        <th>
                            <p>Type</p>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{ if (Model.Types != null)
                        {
                            foreach (var item in Model.Types)
                            {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Id)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                <a asp-action="DeleteType" asp-route-id="@item.Id">Delete</a>
                                            </td>
                                        </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>